package com.natidze.irakli.assign2;

/**
 * Created by Irakli on 01.05.2016.
 */
public class Players {
    public static String [] names = {
            "Walter White", "Jesse Pinkman","Gustavo Fring","Saul Goodman",
            "Hank Schrader","Skyler White","Mike Ermantraut","Tuco Salamanca",
            "Bogdan Wolnetz"
    };

    public static String [] images = {
        "http://vignette4.wikia.nocookie.net/breakingbad/images/e/e7/BB-S5B-Walt-590.jpg/revision/latest?cb=20130928055404",
        "http://www.do-you-prefer.com/webroot/image/profil/jesse-pinkman.jpg",
        "https://upload.wikimedia.org/wikipedia/en/7/7b/Gustavo_fring_breaking_bad.jpg",
        "http://cdn.pastemagazine.com/www/articles/Saul_Goodman.jpg",
        "https://upload.wikimedia.org/wikipedia/en/thumb/c/c1/Hank_Schrader2.jpg/220px-Hank_Schrader2.jpg",
        "http://vignette3.wikia.nocookie.net/breakingbad/images/b/b9/SkylerS5B-Portal.jpg/revision/latest?cb=20130723224438",
        "http://vignette4.wikia.nocookie.net/breakingbad/images/9/9f/Season_4_-_Mike.jpg/revision/latest?cb=20110620221523",
        "http://cs5977.vk.me/u161865446/a_befae7b7.jpg",
        "http://www.anl.gov/sites/anl.gov/files/styles/imagelink_180/public/contributor/headshot/expert-Stan-480x480.jpg?itok=AQJuBfMJ",
    };

    public static String [] descreption = {
        "1Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla tortor. In cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuada",
        "2Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla tortor. In cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu  In cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu  In cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuada",
        "3Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla tortor. In cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuada",
        "4Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla tortor. In cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuada",
        "5Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla tortor. In cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuada",
        "6Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est.  Curabitur id dignissim Donec placerat, nunc eget scelerisque eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla tortor. In cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuada",
        "7Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla tortor. In cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuada",
        "8Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla tortor. In cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuada",
        "9Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien. Cras at velit est. Curabitur id dignissim Donec placerat, nunc eget scelerisque eget scelerisque finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien finibus, orci purus interdum augue, nec fringilla lectus dui quis sapien Curabitur id dignissim Donec placerat, nunc eget scelerisque finibus, orci purus interdum augue, nec fringilla tortor. In cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuadaIn cursus, mauris id condimentum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultricies, quam eu malesuada",
    };


}
